server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file:///E:/Development/eventhub-config
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: health,info